/* Grist API: loaded from the official getgrist.com CDN in index.html; no vendored copy. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { config: {}, log: [], source: null, target: null };
  function setStatus(message, kind = 'neutral', target = $('status')) { target.textContent = message; target.className = `status ${kind}`; }
  function esc(value) { return String(value ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])); }
  function urlFor(path) { return `${String(state.config.baseUrl || '').replace(/\/+$/, '')}/api/docs/${encodeURIComponent(state.config.docId)}/tables/${encodeURIComponent(state.config.tableId)}${path}`; }
  function headers() { return { 'Content-Type': 'application/json', 'Authorization': `Bearer ${state.config.apiKey}` }; }
  async function targetFetch(options = {}) { let response; try { response = await fetch(urlFor('/records'), { ...options, headers: { ...headers(), ...(options.headers || {}) } }); } catch (error) { throw new Error(`Erreur réseau : ${error.message}`); } if (!response.ok) { let detail = ''; try { detail = await response.text(); } catch (_) {} throw new Error(`HTTP ${response.status} ${response.statusText}${detail ? ` — ${detail.slice(0, 300)}` : ''}`); } if (response.status === 204) return null; try { return await response.json(); } catch (_) { return null; } }
  function validConfig() { return state.config.baseUrl && state.config.docId && state.config.tableId && state.config.apiKey; }
  async function readSource() { const tableId = grist.getTable ? await grist.getTable().then(t => t && t.getTableId ? t.getTableId() : undefined) : undefined; const data = await grist.docApi.fetchTable(tableId); const columns = Object.keys(data || {}).filter(k => k !== 'id'); const rowCount = columns.length ? data[columns[0]].length : ((data && data.id) || []).length; state.source = { data, columns, rowCount, tableId: tableId || 'table actuelle' }; $('sourceTable').textContent = state.source.tableId; $('sourceRows').textContent = rowCount; }
  function recordsFromSource(mapped) { return Array.from({ length: state.source.rowCount }, (_, i) => ({ fields: Object.fromEntries(mapped.map(name => [name, state.source.data[name][i]])) })); }
  function targetColumnNames(payload) { const fields = new Set(); if (payload && Array.isArray(payload.records)) payload.records.forEach(r => Object.keys(r.fields || {}).forEach(k => fields.add(k))); if (payload && payload.table && Array.isArray(payload.table.columns)) payload.table.columns.forEach(c => fields.add(c.id || c.colId || c.name)); return [...fields]; }
  async function mapColumns() { const payload = await targetFetch({ method: 'GET' }); state.target = payload; const names = targetColumnNames(payload); if (!names.length) throw new Error('Impossible de lire les colonnes de la table cible (table vide ou droits insuffisants).'); const mapped = state.source.columns.filter(name => names.includes(name)); const missing = state.source.columns.filter(name => !names.includes(name)); $('mappedColumns').textContent = `${mapped.length} / ${state.source.columns.length}`; $('missingNotice').classList.toggle('hidden', !missing.length); $('missingNotice').textContent = missing.length ? `Colonnes source non synchronisées (aucune correspondance côté cible) : ${missing.join(', ')}.` : ''; return mapped; }
  async function testConnection() { if (!validConfig()) return setStatus('Renseignez tous les champs avant de tester.', 'error', $('testStatus')); $('testButton').disabled = true; setStatus('Test de connexion en cours…', 'neutral', $('testStatus')); try { const result = await targetFetch({ method: 'GET' }); const count = result && result.records ? result.records.length : 0; setStatus(`Connexion OK. ${count} ligne(s) actuellement visible(s).`, 'success', $('testStatus')); } catch (error) { setStatus(`Échec du test : ${error.message}`, 'error', $('testStatus')); } finally { $('testButton').disabled = false; } }
  async function sync() { if (!validConfig()) { setStatus('Configurez d’abord la destination.', 'error'); $('configView').classList.remove('hidden'); $('mainView').classList.add('hidden'); return; } if (!confirm('Cette action va écraser toutes les données existantes de la table cible par celles de la table source. Continuer ?')) return; $('syncButton').disabled = true; setStatus('Lecture et vérification du mapping…'); const started = new Date(); let count = 0; try { await readSource(); const mapped = await mapColumns(); const records = recordsFromSource(mapped); count = records.length; const current = state.target && Array.isArray(state.target.records) ? state.target.records.map(r => r.id).filter(Number.isInteger) : []; setStatus('Purge de la table cible…'); if (current.length) await targetFetch({ method: 'DELETE', body: JSON.stringify({ records: current }) }); if (records.length) { setStatus('Réécriture des données…'); await targetFetch({ method: 'POST', body: JSON.stringify({ records }) }); } $('lastSuccess').textContent = new Date().toLocaleString('fr-FR'); $('lastCount').textContent = count; setStatus(`Synchronisation réussie : ${count} ligne(s) écrite(s).`, 'success'); addLog(true, started, count); } catch (error) { setStatus(`La synchronisation a échoué, la table cible peut être incomplète — relancez la synchronisation. ${error.message}`, 'error'); addLog(false, started, error.message); } finally { $('syncButton').disabled = false; } }
  function addLog(ok, at, detail) { state.log.unshift({ ok, at: at.toLocaleTimeString('fr-FR'), detail }); state.log = state.log.slice(0, 5); $('syncLog').innerHTML = state.log.map(x => `<li class="${x.ok ? 'ok' : 'fail'}"><span>${x.ok ? '✓ Succès' : '✕ Échec'}</span><span>${esc(x.at)} · ${esc(x.detail)}</span></li>`).join(''); }
  async function saveOptions() { state.config = { baseUrl: $('baseUrl').value.trim(), docId: $('docId').value.trim(), tableId: $('tableId').value.trim(), apiKey: $('apiKey').value, autoOpen: $('autoOpen').checked }; await grist.widget.setOptions(state.config); setStatus('Configuration enregistrée.', 'success', $('testStatus')); }
  async function init() { grist.ready({ requiredAccess: 'read table' }); state.config = (await grist.widget.getOptions()) || {}; $('baseUrl').value = state.config.baseUrl || ''; $('docId').value = state.config.docId || ''; $('tableId').value = state.config.tableId || ''; $('apiKey').value = state.config.apiKey || ''; $('autoOpen').checked = Boolean(state.config.autoOpen); try { await readSource(); } catch (error) { setStatus(`Lecture de la table source impossible : ${error.message}`, 'error'); } $('syncButton').onclick = sync; $('testButton').onclick = testConnection; $('configForm').onsubmit = async e => { e.preventDefault(); try { await saveOptions(); } catch (error) { setStatus(`Enregistrement impossible : ${error.message}`, 'error', $('testStatus')); } }; $('settingsButton').onclick = () => { $('configView').classList.remove('hidden'); $('mainView').classList.add('hidden'); }; $('closeSettings').onclick = () => { $('configView').classList.add('hidden'); $('mainView').classList.remove('hidden'); }; $('clearButton').onclick = async () => { if (confirm('Supprimer la configuration enregistrée dans ce widget ?')) { state.config = {}; await grist.widget.setOptions({}); location.reload(); } }; if (state.config.autoOpen && validConfig()) await sync(); }
  window.addEventListener('DOMContentLoaded', () => init().catch(error => setStatus(`Initialisation impossible : ${error.message}`, 'error')));
})();
